### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by ltspicer** [NCalu/NCneticCore#1]
When I click Plot/Refresh, "Access violation" appears.
I have already set full access for all users and applications.
Any ideas?

**Comment by NCalu** [comment]
Hi, I think I already saw something like this.
A ViewPortPaint() call is made before the bind() call.
This lead to memory access violation in the graphic pipeline.

I am not sure why this happens, but I fixed it that time checking if the ElementArrayBuffer is of correct size.

In the ViewPortPaint() in ncView.cs add this:

```
try
{
    int bufferSize = 0;
    GL.GetBufferParameter(BufferTarget.ElementArrayBuffer, BufferParameterName.BufferSize, out bufferSize);
    if (ObjCollection.indicedata.Length * sizeof(int) != bufferSize)
    {
        Bind();
    }
}
catch { }
```

just before GL.Flush();

Let me know if you can test it. Thanks

**Comment by ltspicer** [comment]
Thx.
But I have just installed (copy) the dll.
How do I install the plugin directly from github?

**Comment by NCalu** [comment]
Ok,
I updated the code & the dll
Could you try see if it works?
Thanks in advance.

**Comment by ltspicer** [comment]
Have you updated the zip on https://www.ncnetic.com/NCneticNpp.zip too?

**Comment by NCalu** [comment]
yes it is updated

**Comment by ltspicer** [comment]
Hmm. Same issue :(

**Comment by NCalu** [comment]
What is the complete error msg ?

**Comment by ltspicer** [comment]
Here are 2 printscreens ;)

![Auswahl_001](https://github.com/NCalu/NCneticNpp/assets/11616336/43527483-6e4a-4058-95f3-e3935a575bc7)


![Auswahl_001](https://github.com/NCalu/NCneticNpp/assets/11616336/032bde02-92cc-4452-985e-825a05c0ab88)

**Comment by ltspicer** [comment]
![Auswahl_001](https://github.com/NCalu/NCneticNpp/assets/11616336/827a4ded-929a-4323-81dd-d2cd96b5f940)

**Comment by NCalu** [comment]
What graphic card do you use ?

**Comment by ltspicer** [comment]
I use Virtualbox. Graphic controller: VBoxSVGA

**Comment by NCalu** [comment]
This is probably the issue.
You need openGL on your machine.
I think you can get it installing "VirtualBox Guest Additions"
Let me know !

**Comment by ltspicer** [comment]
The "VirtualBox Guest Additions" are allready installed!

Problem solved! I have activated the 3D acceleration :D

Thanks for support!
