### ISSUE TITLE
Support for 4 & 5 axis code?

### ISSUE THREAD

**Issue by CCS86** [NCalu/NCneticCore#5]
Hi there, thank you so much for sharing this plugin with us!

I see some info online that suggests it can support 4 & 5 axis code, but I cannot figure out how to make that work. It seems to be ignoring my C axis positional moves, and I don't see a "machine manager" in the plugin settings.

Thanks!

**Comment by NCalu** [comment]
Hi,

The infos you saw online refers to a more advanced (yet similar) project. 
There is no plan for a 4 or 5 axis support on this project.

Sorry :(

**Comment by CCS86** [comment]
> Hi,
> 
> The infos you saw online refers to a more advanced (yet similar) project. There is no plan for a 4 or 5 axis support on this project.
> 
> Sorry :(


Ah, I see. So, this isn't the same?

![image](https://github.com/NCalu/NCneticNpp/assets/12439543/e145a1fe-921e-40d4-9fc7-22dcd3acd586)

**Comment by NCalu** [comment]
No,

This post is about the stand alone ncnetic version in its first version. Let's call it a discontinued project.
It was packing more features, including some 4&5 axis support.
